### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by caimeng2** [Yingjie4Science/SDGdetector#2]
`my_text <- data.frame(my_col=c('our goal is to end poverty globally', 'this product contributes to slowing down climate change'))`
`SDGdetector(my_text)`

It doesn't work this way, but no error or warning is returned

**Comment by Yingjie4Science** [comment]
@caimeng2 The error prompt should be "argument "col" is missing, with no default". You need to use this

**Comment by Yingjie4Science** [comment]
@caimeng2 I have tested this and it should work now.

**Comment by caimeng2** [comment]
It was a note for an earlier version. Glad you've taken care of it.
