### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by caleblucas** [Yingjie4Science/SDGdetector#3]
@Yingjie4Science Very excited to review your alls paper at JoSS and hope all is well - seems like things are going great.

JoSS wants related packages to be briefly discussed and differentiated ("Do the authors describe how this software compares to other commonly-used packages?") - what about adding a blurb (I think these can even be footnotes) regarding text2sdg and mentioning the differences?

**Comment by Yingjie4Science** [comment]
Thank you, @caleblucas , for taking your time review our paper. This is a great suggestion, which can help make our major contribution stand out more. I have revised the text, and you should be able to see the new added text from this link https://github.com/Yingjie4Science/SDGdetector/commit/3cbb5af904209692d3c80785c4350bea4c602572

**Comment by caleblucas** [comment]
Great, thanks @Yingjie4Science! Is there a way to reproduce the performance metrics provided in the paper/repo (e.g. pg 3 here https://drive.google.com/file/d/1EHUV6Jc3N4A-IshKU4dbxtIqlfj50mzi/view)?

**Comment by caleblucas** [comment]
Also, ` sdg_icon()` is handy! Nice idea.

**Comment by caleblucas** [comment]
@Yingjie4Science can you please add a citation to `text2sdg` in the references section paper?

**Comment by Yingjie4Science** [comment]
Hi @caleblucas, thanks again for the suggestions! 

- We have added the code and data for reproducing the performance metrics, see https://github.com/Yingjie4Science/SDGdetector/commit/f3148f95f852fd75b773f433a45b6dfbd5cc248a
- I am glad you like this small function! I find it very useful and handy too!
- We cited `text2sdg` in other sections and I agree we need to add a citation to `text2sdg` in the paragraph where we discussed the key differences between `SDGdetector` and `text2sdg`. See our revision here https://github.com/Yingjie4Science/SDGdetector/commit/1932a5303d1664baa779689ba9a2cc64cd46d48d

**Comment by caleblucas** [comment]
@Yingjie4Science fantastic! thank you. can you please link the performance metric files in the readme (probably next to where the supplementary document is linked now?) and note somewhere in the paper that the data/code to replicate the results are available in the repo?

**Comment by Yingjie4Science** [comment]
@caleblucas Yes! We have added related text in the repo's readme (https://github.com/Yingjie4Science/SDGdetector/commit/b87c4e5fe24b4eb3c077ac263bfbd22f18b3da1d) and in the paper (see https://github.com/Yingjie4Science/SDGdetector/commit/56cf11fbe3462fd879b0055c17b2f8892807ee9c)

We have also added more tests per another reviewer's suggestions, and the current test coverage is 93.45%. See https://github.com/Yingjie4Science/SDGdetector/commit/bfed791e877e82ceafb7bbe25b0ebfad95b11b2a

**Comment by caleblucas** [comment]
Great @Yingjie4Science! Thanks. I noticed the other reviewer's great suggestions and extending the test coverage was a great improvement.
