### ISSUE TITLE
Where does the "Value" Column in "sdgstat" comes from? 

### ISSUE THREAD

**Issue by v-gestern** [Yingjie4Science/SDGdetector#5]
Thank you for creating an providing this super cool package! 

Unfortunately I can´t perform all given functionalities on my own data. 
If I run SDGdetector on my data, it returns a df with the the new column "sdg" where the identified SDGs are shown. But it doesn´t return  the values described in the help function ("Data frame with the same information as df and 18 extra columns: 17 columns marking the number of occurrence of each of the 17 SDGs and one column match_detail listing details of specific targets."). 

And where do I get the "Value" column from to perform plot_sdg_bar on my own data?

**Comment by v-gestern** [comment]
@Yingjie4Science Thank you for the update. I re-installed the package and tried to use the new function, but I got this error message: "Error in summarize_sdg(d, sum_by = "goal", quiet = FALSE) : 
  could not find function "summarize_sdg" even though summarize_sdg is available in the package Help/Description


![Bildschirmfoto vom 2023-05-22 17-48-11](https://github.com/Yingjie4Science/SDGdetector/assets/93721799/8bc0437d-03ad-4bc9-adfd-2ddfa4b28c1c)

**Comment by Yingjie4Science** [comment]
@v-gestern did you re-installed via cran or GitHub version? You may want to use the GitHub development version because getting the updated version on CRAN would take a while.

**Comment by v-gestern** [comment]
@Yingjie4Science I used the code you are suggesting in your README.md 

if (!require("remotes")) {
  install.packages("remotes")
}

remotes::install_github("Yingjie4Science/SDGdetector")

**Comment by Yingjie4Science** [comment]
@v-gestern could you test it again? I found a testing error, and guess that could be the reason that caused the error. I have fixed it and tested it on my end. Hope the updated one can work on your machine.

**Comment by Yingjie4Science** [comment]
@v-gestern you may try [CRAN version](https://cran.r-project.org/web/packages/SDGdetector/index.html) and see if it works or not. Otherwise, see the way above.

**Comment by caimeng2** [comment]
@Yingjie4Science it works for me fine.
<img width="799" alt="Screenshot 2023-05-24 at 2 16 10 PM" src="https://github.com/Yingjie4Science/SDGdetector/assets/51100838/3c522ce5-bebb-4bb2-919c-99f26c6429c4">

installed from Github

**Comment by Yingjie4Science** [comment]
@caimeng2 Thanks!!! @v-gestern see the above messages, we have updated the CRAN version.
